// apps/vue-demo/src/components/kit/XAvatar.vue
<script setup lang="ts">
/**
 * XAvatar 头像：展示用户形象，支持圆形/方形、五档尺寸、图片与图标。
 */
import type { HTMLAttributes } from 'vue'
import { computed } from 'vue'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { cn } from '@/lib/utils'

type AvatarShape = 'circle' | 'square'
type AvatarSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl'

const props = withDefaults(defineProps<{
  /** 头像形状 */
  shape?: AvatarShape
  /** 头像尺寸 */
  size?: AvatarSize
  /** 图片地址 */
  src?: string
  /** 图片描述文本 */
  alt?: string
  class?: HTMLAttributes['class']
}>(), {
  shape: 'circle',
  size: 'md',
})

const emit = defineEmits<{
  /** 图片加载失败回调 */
  error: [event: Event]
}>()

const sizeClasses: Record<AvatarSize, string> = {
  xs: 'size-5 text-xs',
  sm: 'size-6 text-xs',
  md: 'size-8 text-sm',
  lg: 'size-10 text-base',
  xl: 'size-12 text-lg',
}

const shapeClass = computed(() => (props.shape === 'circle' ? 'rounded-full' : 'rounded-md'))
</script>

<template>
  <Avatar :class="cn(shapeClass, sizeClasses[size], props.class)">
    <AvatarImage v-if="src" :src="src" :alt="alt ?? 'avatar'" @error="emit('error', $event)" />
    <AvatarFallback :class="shapeClass">
      <slot name="icon" />
      <slot />
    </AvatarFallback>
  </Avatar>
</template>

// packages/react/src/components/kit/x-avatar.tsx
/**
 * XAvatar 头像：展示用户形象，支持圆形/方形、五档尺寸、图片与图标。
 */
import * as React from "react"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { cn } from "@/lib/utils"

export type XAvatarShape = "circle" | "square"
export type XAvatarSize = "xs" | "sm" | "md" | "lg" | "xl"

const avatarSizeClasses: Record<XAvatarSize, string> = {
  xs: "size-5 text-xs",
  sm: "size-6 text-xs",
  md: "size-8 text-sm",
  lg: "size-10 text-base",
  xl: "size-12 text-lg",
}

export interface XAvatarProps extends Omit<React.ComponentProps<typeof Avatar>, "size" | "onError"> {
  /** 头像形状 */
  shape?: XAvatarShape
  /** 头像尺寸 */
  size?: XAvatarSize
  /** 图片地址 */
  src?: string
  /** 图标 */
  icon?: React.ReactNode
  /** 图片加载失败回调 */
  onError?: (event: React.SyntheticEvent<HTMLImageElement>) => void
}

export function XAvatar({
  shape = "circle",
  size = "md",
  src,
  icon,
  onError,
  className,
  children,
  ...props
}: XAvatarProps) {
  return (
    <Avatar
      className={cn(
        shape === "circle" ? "rounded-full" : "rounded-md",
        avatarSizeClasses[size],
        className,
      )}
      {...props}
    >
      {src ? (
        <AvatarImage src={src} alt={props["aria-label"] ?? "avatar"} onError={onError} />
      ) : null}
      <AvatarFallback className={cn(shape === "circle" ? "rounded-full" : "rounded-md")}>
        {icon ?? children}
      </AvatarFallback>
    </Avatar>
  )
}
