// packages/vue/src/components/kit/XInputRating.vue
<script setup lang="ts">
/**
 * XInputRating 评分：以星标形式进行评分输入，支持半星与自定义图标插槽。
 */
import type { HTMLAttributes } from 'vue'
import { Star } from '@lucide/vue'
import { cn } from '@/lib/utils'

const props = withDefaults(defineProps<{
  /** 评分值 */
  modelValue?: number
  /** 最大分值 */
  max?: number
  /** 允许半星 */
  allowHalf?: boolean
  /** 是否禁用 */
  disabled?: boolean
  class?: HTMLAttributes['class']
}>(), {
  modelValue: 0,
  max: 5,
})

const emit = defineEmits<{
  'update:modelValue': [value: number]
  /** 评分变化回调 */
  change: [value: number]
}>()

function pick(index: number, event: MouseEvent) {
  if (props.disabled) return
  const target = event.currentTarget as HTMLElement
  const half = props.allowHalf && event.clientX > target.getBoundingClientRect().left + target.offsetWidth / 2
  const next = half && props.allowHalf ? index + 0.5 : index + 1
  emit('update:modelValue', next)
  emit('change', next)
}
</script>

<template>
  <span
    role="radiogroup"
    aria-label="rating"
    :class="cn('inline-flex items-center gap-0.5', disabled && 'pointer-events-none opacity-60', props.class)"
  >
    <button
      v-for="index in max"
      :key="index"
      type="button"
      :aria-label="`${index} 星`"
      class="cursor-pointer outline-none transition-colors hover:text-primary-6 focus-visible:text-primary-6"
      @click="pick(index - 1, $event)"
    >
      <slot
        name="item"
        :index="index - 1"
        :filled="modelValue >= index"
        :half="allowHalf && modelValue >= index - 0.5 && modelValue < index"
      >
        <span class="relative inline-flex" aria-hidden="true">
          <Star class="size-5 text-border" />
          <Star
            v-if="allowHalf && modelValue >= index - 0.5 && modelValue < index"
            class="absolute inset-0 size-5 fill-warning-6 text-warning-6 [clip-path:inset(0_50%_0_0)]"
          />
          <Star v-if="modelValue >= index" class="absolute inset-0 size-5 fill-warning-6 text-warning-6" />
        </span>
      </slot>
    </button>
  </span>
</template>

// packages/react/src/components/kit/x-input-rating.tsx
/**
 * XInputRating 评分：以星标形式进行评分输入，支持半星与自定义图标。
 */
import * as React from "react"
import { Star } from "lucide-react"
import { cn } from "@/lib/utils"

export interface XInputRatingProps {
  /** 评分值 */
  value?: number
  /** 默认评分 */
  defaultValue?: number
  /** 最大分值 */
  max?: number
  /** 允许半星 */
  allowHalf?: boolean
  /** 是否禁用 */
  disabled?: boolean
  /** 评分变化回调 */
  onChange?: (value: number) => void
  /** 自定义图标渲染 */
  item?: (state: { filled: boolean; half: boolean }) => React.ReactNode
  className?: string
}

export function XInputRating({
  value,
  defaultValue = 0,
  max = 5,
  allowHalf = false,
  disabled = false,
  onChange,
  item,
  className,
}: XInputRatingProps) {
  const [innerValue, setInnerValue] = React.useState(defaultValue)
  const current = value ?? innerValue

  const pick = (index: number, half: boolean) => {
    if (disabled) return
    const next = half && allowHalf ? index + 0.5 : index + 1
    if (value == null) setInnerValue(next)
    onChange?.(next)
  }

  const renderStar = (index: number) => {
    const filled = current >= index + 1
    const half = !filled && allowHalf && current >= index + 0.5
    if (item) return item({ filled, half })
    return (
      <span className="relative inline-flex" aria-hidden="true">
        <Star className="size-5 text-border" />
        {half && (
          <Star className="absolute inset-0 size-5 fill-warning-6 text-warning-6 [clip-path:inset(0_50%_0_0)]" />
        )}
        {filled && <Star className="absolute inset-0 size-5 fill-warning-6 text-warning-6" />}
      </span>
    )
  }

  return (
    <span
      role="radiogroup"
      aria-label="rating"
      className={cn("inline-flex items-center gap-0.5", disabled && "pointer-events-none opacity-60", className)}
    >
      {Array.from({ length: max }, (_, index) => (
        <button
          key={index}
          type="button"
          aria-label={`${index + 1} 星`}
          onClick={(event) => pick(index, allowHalf && event.clientX > event.currentTarget.getBoundingClientRect().left + event.currentTarget.offsetWidth / 2)}
          className="cursor-pointer outline-none transition-colors hover:text-primary-6 focus-visible:text-primary-6"
        >
          {renderStar(index)}
        </button>
      ))}
    </span>
  )
}
