// apps/react-demo/src/components/kit/x-input.tsx
import * as React from "react"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"

export type XInputSize = "sm" | "md"
export type XInputStatus = "error" | "warning"

const inputSizeClasses: Record<XInputSize, string> = {
  sm: "h-7 px-2 text-sm",
  md: "h-9 px-3 text-sm",
}

const inputStatusClasses: Record<XInputStatus, string> = {
  error:
    "border-error-6 focus-visible:border-error-6 focus-visible:ring-error-6/20 aria-invalid:border-error-6",
  warning:
    "border-warning-6 focus-visible:border-warning-6 focus-visible:ring-warning-6/20 aria-invalid:border-warning-6",
}

export interface XInputProps extends Omit<React.ComponentProps<typeof Input>, "size" | "prefix"> {
  /** 控件尺寸 */
  size?: XInputSize
  /** 校验状态 */
  status?: XInputStatus
  /** 前置图标 */
  prefix?: React.ReactNode
  /** 后置图标 */
  suffix?: React.ReactNode
  /** 前置标签 */
  addonBefore?: React.ReactNode
  /** 后置标签 */
  addonAfter?: React.ReactNode
}

export const XInput = React.forwardRef<HTMLInputElement, XInputProps>(function XInput(
  { size = "md", status, prefix, suffix, addonBefore, addonAfter, className, ...props },
  ref,
) {
  const inner = (
    <span className="relative flex w-full items-center">
      {prefix != null && (
        <span className="pointer-events-none absolute left-3 flex items-center text-muted-foreground [&_svg]:size-4">
          {prefix}
        </span>
      )}
      <Input
        ref={ref}
        className={cn(
          inputSizeClasses[size],
          prefix != null && "pl-9",
          suffix != null && "pr-9",
          status && inputStatusClasses[status],
          className,
        )}
        {...props}
      />
      {suffix != null && (
        <span className="pointer-events-none absolute right-3 flex items-center text-muted-foreground [&_svg]:size-4">
          {suffix}
        </span>
      )}
    </span>
  )

  if (addonBefore == null && addonAfter == null) return inner

  return (
    <span className="flex w-full items-stretch">
      {addonBefore != null && (
        <span className="inline-flex items-center rounded-l-lg border border-r-0 border-input bg-muted px-3 text-sm text-muted-foreground">
          {addonBefore}
        </span>
      )}
      <span
        className={cn(
          "flex-1",
          addonBefore != null && "[&_input]:rounded-l-none",
          addonAfter != null && "[&_input]:rounded-r-none",
        )}
      >
        {inner}
      </span>
      {addonAfter != null && (
        <span className="inline-flex items-center rounded-r-lg border border-l-0 border-input bg-muted px-3 text-sm text-muted-foreground">
          {addonAfter}
        </span>
      )}
    </span>
  )
})

// packages/vue/src/components/kit/XInput.vue
<script setup lang="ts">
/**
 * XInput 输入框：shadcn-vue input 原子的二次封装。
 * 支持前缀/后缀图标、前后置标签（addon）与 error / warning 校验状态。
 */
import type { HTMLAttributes } from 'vue'
import { useTemplateRef } from 'vue'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'

type InputSize = 'sm' | 'md'
type InputStatus = 'error' | 'warning'

const props = withDefaults(defineProps<{
  /** 控件尺寸 */
  size?: InputSize
  /** 校验状态 */
  status?: InputStatus
  /** 占位提示文字 */
  placeholder?: string
  /** 是否禁用 */
  disabled?: boolean
  /** 最大输入长度 */
  maxLength?: number
  class?: HTMLAttributes['class']
}>(), {
  size: 'md',
})

const sizeClasses: Record<InputSize, string> = {
  sm: 'h-7 px-2 text-sm',
  md: 'h-9 px-3 text-sm',
}

const statusClasses: Record<InputStatus, string> = {
  error: 'border-error-6 focus-visible:border-error-6 focus-visible:ring-error-6/20',
  warning: 'border-warning-6 focus-visible:border-warning-6 focus-visible:ring-warning-6/20',
}

const inputRef = useTemplateRef<HTMLInputElement>('inputRef')

/** 使输入框获得焦点 */
function focus() {
  inputRef.value?.focus()
}

/** 使输入框失去焦点 */
function blur() {
  inputRef.value?.blur()
}

/** 选中输入框内容 */
function select() {
  inputRef.value?.select()
}

defineExpose({ focus, blur, select })
</script>

<template>
  <span class="flex w-full items-stretch">
    <span
      v-if="$slots.addonBefore"
      class="inline-flex items-center rounded-l-lg border border-r-0 border-input bg-muted px-3 text-sm text-muted-foreground"
    >
      <slot name="addonBefore" />
    </span>
    <span class="relative flex w-full min-w-0 flex-1 items-center" :class="cn($slots.addonBefore && '[&_input]:rounded-l-none', $slots.addonAfter && '[&_input]:rounded-r-none')">
      <span v-if="$slots.prefix" class="pointer-events-none absolute left-3 flex items-center text-muted-foreground [&_svg]:size-4">
        <slot name="prefix" />
      </span>
      <Input
        ref="inputRef"
        :class="cn(
          sizeClasses[size],
          $slots.prefix && 'pl-9',
          $slots.suffix && 'pr-9',
          status && statusClasses[status],
          props.class,
        )"
        :disabled="disabled"
        :maxlength="maxLength"
        :placeholder="placeholder"
      />
      <span v-if="$slots.suffix" class="pointer-events-none absolute right-3 flex items-center text-muted-foreground [&_svg]:size-4">
        <slot name="suffix" />
      </span>
    </span>
    <span
      v-if="$slots.addonAfter"
      class="inline-flex items-center rounded-r-lg border border-l-0 border-input bg-muted px-3 text-sm text-muted-foreground"
    >
      <slot name="addonAfter" />
    </span>
  </span>
</template>
