// apps/docs/demos/react/button-sizes.tsx
import { XButton, type XButtonSize } from "@/components/kit";

const sizes: XButtonSize[] = ["xs", "sm", "md", "lg", "xl"];

export default function ButtonSizes() {
  return (
    <div className="flex flex-wrap items-center gap-3">
      {sizes.map((size) => (
        <XButton key={size} size={size}>{size}</XButton>
      ))}
    </div>
  );
}

// apps/docs/demos/vue/button-sizes.vue
<script setup lang="ts">
import XButton from '@/components/kit/XButton.vue'

const sizes = ['xs', 'sm', 'md', 'lg', 'xl'] as const
</script>

<template>
  <div class="flex flex-wrap items-center gap-3">
    <XButton v-for="size in sizes" :key="size" :size="size">{{ size }}</XButton>
  </div>
</template>
