// apps/docs/demos/react/button-colors.tsx
import { XButton, type XButtonColor } from "@/components/kit";

const colors: XButtonColor[] = ["primary", "secondary", "neutral", "success", "info", "warning", "error"];

export default function ButtonColors() {
  return (
    <div className="flex flex-wrap items-center gap-3">
      {colors.map((color) => (
        <XButton key={color} color={color}>{color}</XButton>
      ))}
    </div>
  );
}

// apps/docs/demos/vue/button-colors.vue
<script setup lang="ts">
import { XButton } from '@/components/kit'

const colors = ['primary', 'secondary', 'neutral', 'success', 'info', 'warning', 'error'] as const
</script>

<template>
  <div class="flex flex-wrap items-center gap-3">
    <XButton v-for="color in colors" :key="color" :color="color">{{ color }}</XButton>
  </div>
</template>
