// packages/vue/src/components/kit/XCheckbox.vue
<script setup lang="ts">
/**
 * XCheckbox 多选框：shadcn-vue checkbox 原子的二次封装。
 * 支持半选状态与 label 插槽。
 */
import type { HTMLAttributes } from 'vue'
import { computed } from 'vue'
import { Checkbox } from '@/components/ui/checkbox'
import { Label } from '@/components/ui/label'
import { cn } from '@/lib/utils'

const props = withDefaults(defineProps<{
  /** 是否禁用 */
  disabled?: boolean
  /** 半选状态 */
  indeterminate?: boolean
  /** 选项的值 */
  value?: string | number
  class?: HTMLAttributes['class']
}>(), {
  indeterminate: false,
})

const model = defineModel<boolean | 'indeterminate'>({ default: false })

const checkedValue = computed(() => (props.indeterminate ? 'indeterminate' : model.value))
</script>

<template>
  <span :class="cn('flex items-center gap-2', props.class)">
    <Checkbox
      :model-value="checkedValue"
      :disabled="disabled"
      :value="value == null ? undefined : String(value)"
      @update:model-value="model = $event"
    />
    <Label v-if="$slots.label" class="text-sm font-normal">
      <slot name="label" />
    </Label>
  </span>
</template>

// apps/react-demo/src/components/kit/x-checkbox.tsx
import * as React from "react"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { cn } from "@/lib/utils"

export interface XCheckboxProps extends Omit<React.ComponentProps<typeof Checkbox>, "value" | "checked"> {
  /** 是否选中 */
  checked?: boolean
  /** 半选状态 */
  indeterminate?: boolean
  /** 选项文字 */
  label?: React.ReactNode
  /** 选项的值 */
  value?: string | number
}

export const XCheckbox = React.forwardRef<HTMLButtonElement, XCheckboxProps>(function XCheckbox(
  { indeterminate = false, label, value, id, className, checked, ...props },
  ref,
) {
  return (
    <span className={cn("flex items-center gap-2", className)}>
      <Checkbox
        ref={ref}
        id={id}
        value={value == null ? undefined : String(value)}
        checked={checked}
        indeterminate={indeterminate}
        {...props}
      />
      {label != null && (
        <Label htmlFor={id} className="text-sm font-normal">
          {label}
        </Label>
      )}
    </span>
  )
})
