// packages/vue/src/components/kit/XScrollArea.vue
<script setup lang="ts">
/**
 * XScrollArea 滚动区域：内容溢出时可滚动的区域。
 */
import type { HTMLAttributes } from 'vue'
import { useTemplateRef } from 'vue'
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area'
import { cn } from '@/lib/utils'

const props = withDefaults(defineProps<{
  /** 区域高度 */
  height?: number | string
  /** 滚动条显示时机 */
  type?: 'auto' | 'always' | 'hover'
  class?: HTMLAttributes['class']
}>(), {
  type: 'auto',
})

const viewportRef = useTemplateRef<HTMLDivElement>('viewportRef')

/** 滚动到指定位置 */
function scrollTo(top: number) {
  viewportRef.value?.scrollTo({ top })
}

defineExpose({ scrollTo })
</script>

<template>
  <ScrollArea
    :class="cn(
      'w-full',
      type === 'always' && '[&_[data-slot=scroll-area-scrollbar]]:opacity-100',
      type === 'hover' && '[&_[data-slot=scroll-area-scrollbar]]:opacity-0 hover:[&_[data-slot=scroll-area-scrollbar]]:opacity-100',
      props.class,
    )"
    :style="height != null ? { height: typeof height === 'number' ? `${height}px` : height } : undefined"
  >
    <div ref="viewportRef" class="flex flex-col gap-1 p-1">
      <slot />
    </div>
    <ScrollBar />
  </ScrollArea>
</template>

// apps/react-demo/src/components/kit/x-scroll-area.tsx
import * as React from "react"
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area"
import { cn } from "@/lib/utils"

export interface XScrollAreaProps {
  /** 区域高度 */
  height?: number | string
  /** 滚动条显示时机 */
  type?: "auto" | "always" | "hover"
  /** 滚动内容 */
  children?: React.ReactNode
  className?: string
}

export interface XScrollAreaApi {
  scrollTo: (top: number) => void
}

export const XScrollArea = React.forwardRef<XScrollAreaApi, XScrollAreaProps>(function XScrollArea(
  { height, type = "auto", children, className },
  ref,
) {
  const viewportRef = React.useRef<HTMLDivElement>(null)

  React.useImperativeHandle(ref, () => ({
    scrollTo: (top: number) => {
      viewportRef.current?.scrollTo({ top })
    },
  }))

  return (
    <ScrollArea
      className={cn(
        "w-full",
        type === "always" && "[&_[data-slot=scroll-area-scrollbar]]:opacity-100",
        type === "hover" && "[&_[data-slot=scroll-area-scrollbar]]:opacity-0 hover:[&_[data-slot=scroll-area-scrollbar]]:opacity-100",
        className,
      )}
      style={height != null ? { height } : undefined}
    >
      <div ref={viewportRef} className="flex flex-col gap-1 p-1">
        {children}
      </div>
      <ScrollBar />
    </ScrollArea>
  )
})

/* ============================ vben 风格 hook ============================ */

export interface XScrollAreaInstanceApi {
  /** 滚动到指定位置 */
  scrollTo: (top: number) => void
}

/** 创建与 api 绑定的滚动区域：调用即得 [ScrollArea, scrollAreaApi] */
export function useXScrollArea(options: Partial<XScrollAreaProps> = {}) {
  const areaRef = React.useRef<XScrollAreaApi>(null)
  const api = React.useMemo<XScrollAreaInstanceApi>(
    () => ({
      scrollTo: (top: number) => areaRef.current?.scrollTo(top),
    }),
    [],
  )

  const ScrollArea = React.useMemo(() => {
    return function BoundScrollArea(props: Partial<XScrollAreaProps> = {}) {
      return <XScrollArea ref={areaRef} {...options} {...props} />
    }
  }, [])

  return [ScrollArea, api] as const
}
