// packages/vue/src/components/kit/XTable.vue
<script setup lang="ts">
/**
 * XTable 表格：展示行列数据，支持状态标签、加载与分页。
 */
import type { HTMLAttributes } from 'vue'
import { computed, ref } from 'vue'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import XPagination from '@/components/kit/XPagination.vue'
import XSkeleton from '@/components/kit/XSkeleton.vue'
import { cn } from '@/lib/utils'

export interface TableColumnData {
  /** 列 key */
  key: string
  /** 列标题 */
  title: string
  /** 列宽 */
  width?: number | string
}

const props = withDefaults(defineProps<{
  /** 表格列配置 */
  columns: TableColumnData[]
  /** 数据源数组 */
  dataSource: Record<string, unknown>[]
  /** 行唯一键 */
  rowKey?: string
  /** 加载状态 */
  loading?: boolean
  /** 表格尺寸 */
  size?: 'sm' | 'md'
  /** 分页配置（false 关闭分页） */
  pagination?: { current?: number; pageSize?: number; total?: number } | false
  class?: HTMLAttributes['class']
}>(), {
  rowKey: 'key',
  loading: false,
  size: 'md',
  pagination: () => ({ pageSize: 10 }),
})

const emit = defineEmits<{
  /** 页码或每页条数变化回调 */
  pageChange: [page: number, pageSize: number]
}>()

const innerPage = ref(1)

const pageSize = computed(() => (props.pagination ? props.pagination.pageSize ?? 10 : props.dataSource.length))
const total = computed(() => (props.pagination ? props.pagination.total ?? props.dataSource.length : props.dataSource.length))
const current = computed(() => (props.pagination ? props.pagination.current ?? innerPage.value : 1))

const rows = computed(() =>
  props.pagination
    ? props.dataSource.slice((current.value - 1) * pageSize.value, current.value * pageSize.value)
    : props.dataSource,
)

const cellClasses = computed(() => (props.size === 'sm' ? 'px-2 py-1.5 text-xs' : 'px-3 py-2.5 text-sm'))

function onPageChange(page: number, size: number) {
  if (props.pagination && props.pagination.current == null) innerPage.value = page
  emit('pageChange', page, size)
}

/** 重新加载数据 */
function reload() {
  if (props.pagination && props.pagination.current == null) innerPage.value = 1
}

defineExpose({ reload })
</script>

<template>
  <div :class="cn('flex flex-col gap-2', props.class)">
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead v-for="column in columns" :key="column.key" :style="{ width: column.width }">
            <slot name="headerCell" :column="column">{{ column.title }}</slot>
          </TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow v-if="loading" v-for="index in 3" :key="`skeleton-${index}`">
          <TableCell v-for="column in columns" :key="column.key" :class="cellClasses">
            <XSkeleton variant="text" class="h-4" />
          </TableCell>
        </TableRow>
        <TableRow v-else v-for="(record, index) in rows" :key="String(record[rowKey] ?? index)">
          <TableCell v-for="column in columns" :key="column.key" :class="cellClasses">
            <slot name="bodyCell" :column="column" :record="record" :index="index">
              {{ record[column.key] }}
            </slot>
          </TableCell>
        </TableRow>
        <TableRow v-if="!loading && rows.length === 0">
          <TableCell :colspan="columns.length" class="py-8 text-center text-muted-foreground">
            <slot name="emptyText">暂无数据</slot>
          </TableCell>
        </TableRow>
      </TableBody>
    </Table>
    <div v-if="pagination !== false && total > 0" class="flex justify-end">
      <XPagination :current="current" :total="total" :page-size="pageSize" @change="onPageChange" />
    </div>
  </div>
</template>

// apps/react-demo/src/components/kit/x-table.tsx
import * as React from "react"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { XPagination } from "@/components/kit/x-pagination"
import { XSkeleton } from "@/components/kit/x-skeleton"
import { createBoundStore, useBoundStore } from "@/lib/kit/bound-store"
import { cn } from "@/lib/utils"

export interface XTableColumn<T> {
  /** 列 key */
  key: string
  /** 列标题 */
  title: React.ReactNode
  /** 列宽 */
  width?: number | string
  /** 自定义单元格渲染 */
  render?: (value: unknown, record: T, index: number) => React.ReactNode
}

export interface XTableProps<T extends Record<string, unknown>> {
  /** 表格列配置 */
  columns?: XTableColumn<T>[]
  /** 数据源数组 */
  dataSource?: T[]
  /** 行唯一键 */
  rowKey?: string
  /** 加载状态 */
  loading?: boolean
  /** 表格尺寸 */
  size?: "sm" | "md"
  /** 分页配置（false 关闭分页） */
  pagination?: { current?: number; pageSize?: number; total?: number } | false
  /** 页码或每页条数变化回调 */
  onPageChange?: (page: number, pageSize: number) => void
  /** 空数据提示 */
  emptyText?: React.ReactNode
  className?: string
}

export function XTable<T extends Record<string, unknown>>({
  columns = [],
  dataSource = [],
  rowKey = "key",
  loading = false,
  size = "md",
  pagination,
  onPageChange,
  emptyText = "暂无数据",
  className,
}: XTableProps<T>) {
  const [innerPage, setInnerPage] = React.useState(1)
  const pageSize = pagination ? pagination.pageSize ?? 10 : dataSource.length
  const total = pagination ? pagination.total ?? dataSource.length : dataSource.length
  const current = pagination ? pagination.current ?? innerPage : 1

  const rows = pagination
    ? dataSource.slice((current - 1) * pageSize, current * pageSize)
    : dataSource

  const cellClasses = size === "sm" ? "px-2 py-1.5 text-xs" : "px-3 py-2.5 text-sm"

  return (
    <div className={cn("flex flex-col gap-2", className)}>
      <Table>
        <TableHeader>
          <TableRow>
            {columns.map((column) => (
              <TableHead key={column.key} style={{ width: column.width }}>
                {column.title}
              </TableHead>
            ))}
          </TableRow>
        </TableHeader>
        <TableBody>
          {loading
            ? Array.from({ length: 3 }, (_, index) => (
                <TableRow key={`skeleton-${index}`}>
                  {columns.map((column) => (
                    <TableCell key={column.key} className={cellClasses}>
                      <XSkeleton variant="text" className="h-4" />
                    </TableCell>
                  ))}
                </TableRow>
              ))
            : rows.map((record, index) => (
                <TableRow key={String(record[rowKey] ?? index)}>
                  {columns.map((column) => (
                    <TableCell key={column.key} className={cellClasses}>
                      {column.render ? column.render(record[column.key], record, index) : (record[column.key] as React.ReactNode)}
                    </TableCell>
                  ))}
                </TableRow>
              ))}
          {!loading && rows.length === 0 && (
            <TableRow>
              <TableCell colSpan={columns.length} className="py-8 text-center text-muted-foreground">
                {emptyText}
              </TableCell>
            </TableRow>
          )}
        </TableBody>
      </Table>
      {pagination !== false && total > 0 && (
        <div className="flex justify-end">
          <XPagination
            current={current}
            total={total}
            pageSize={pageSize}
            onChange={(page, size) => {
              if (pagination && pagination.current == null) setInnerPage(page)
              onPageChange?.(page, size)
            }}
          />
        </div>
      )}
    </div>
  )
}

/* ============================ vben 风格 hook ============================ */

export interface XTableInstanceApi {
  /** 加载状态 */
  loading: boolean
  /** 当前页码 */
  page: number
  /** 设置加载状态 */
  setLoading: (loading: boolean) => void
  /** 重新加载（回到第一页并触发 onReload） */
  reload: () => void
  /** 跳转页码 */
  setPage: (page: number) => void
}

/** 创建与 api 绑定的表格：调用即得 [Table, tableApi] */
export function useXTable<T extends Record<string, unknown>>(
  options: Partial<XTableProps<T>> & { onReload?: () => void } = {},
) {
  const { onReload, ...componentProps } = options
  const store = React.useState(() =>
    createBoundStore({
      loading: componentProps.loading ?? false,
      page: componentProps.pagination !== false ? (componentProps.pagination?.current ?? 1) : 1,
    }),
  )[0]

  const api = React.useMemo<XTableInstanceApi>(
    () => ({
      get loading() {
        return store.get().loading
      },
      get page() {
        return store.get().page
      },
      setLoading: (loading) => store.set({ loading }),
      reload: () => {
        store.set({ page: 1, loading: true })
        onReload?.()
      },
      setPage: (page) => store.set({ page }),
    }),
    [],
  )

  const Table = React.useMemo(() => {
    return function BoundTable(props: Partial<XTableProps<T>> = {}) {
      const state = useBoundStore(store)
      const pagination =
        props.pagination === false
          ? false
          : { ...(componentProps.pagination ?? {}), ...(props.pagination ?? {}), current: state.page }
      return (
        <XTable
          {...componentProps}
          {...props}
          loading={state.loading}
          pagination={pagination}
          onPageChange={(page) => store.set({ page })}
        />
      )
    }
  }, [])

  return [Table, api] as const
}
