// packages/react/src/components/kit/x-pin-input.tsx
/**
 * XPinInput 验证码输入：shadcn input-otp 原子的二次封装。
 * 分段输入验证码，输入完成触发 onComplete。
 */
import * as React from "react"
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@/components/ui/input-otp"
import { cn } from "@/lib/utils"

export interface XPinInputProps {
  /** 绑定值 */
  value?: string
  /** 默认值 */
  defaultValue?: string
  /** 位数 */
  length?: number
  /** 是否掩码 */
  mask?: boolean
  /** 是否禁用 */
  disabled?: boolean
  /** 值变化回调 */
  onChange?: (value: string) => void
  /** 输入完成回调 */
  onComplete?: (value: string) => void
  className?: string
}

export function XPinInput({
  value,
  defaultValue = "",
  length = 6,
  mask = false,
  disabled = false,
  onChange,
  onComplete,
  className,
}: XPinInputProps) {
  const [innerValue, setInnerValue] = React.useState(defaultValue)
  const current = value ?? innerValue

  const handleChange = (next: string) => {
    if (value == null) setInnerValue(next)
    onChange?.(next)
    if (next.length === length) onComplete?.(next)
  }

  return (
    <InputOTP
      maxLength={length}
      value={current}
      disabled={disabled}
      onChange={handleChange}
      onComplete={onComplete}
      className={cn(
        "gap-2",
        mask && "[&_[data-slot=input-otp-slot]]:text-transparent",
        className,
      )}
    >
      <InputOTPGroup>
        {Array.from({ length }, (_, index) => (
          <React.Fragment key={index}>
            {index === Math.floor(length / 2) && index > 0 && <InputOTPSeparator />}
            <InputOTPSlot
              index={index}
              className="h-10 w-10 rounded-lg border-input text-base"
            />
          </React.Fragment>
        ))}
      </InputOTPGroup>
    </InputOTP>
  )
}

// apps/vue-demo/src/components/kit/XPinInput.vue
<script setup lang="ts">
/**
 * XPinInput 验证码输入：shadcn-vue input-otp 原子的二次封装。
 * 分段输入验证码，输入完成触发 complete。
 */
import type { HTMLAttributes } from 'vue'
import { InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot } from '@/components/ui/input-otp'
import { cn } from '@/lib/utils'

const props = withDefaults(defineProps<{
  /** 绑定值 */
  modelValue?: string
  /** 位数 */
  length?: number
  /** 是否掩码 */
  mask?: boolean
  /** 是否禁用 */
  disabled?: boolean
  class?: HTMLAttributes['class']
}>(), {
  modelValue: '',
  length: 6,
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  /** 输入完成回调 */
  complete: [value: string]
}>()
</script>

<template>
  <InputOTP
    :model-value="modelValue"
    :maxlength="length"
    :disabled="disabled"
    :class="cn('gap-2', mask && '[&_[data-slot=input-otp-slot]]:text-transparent', props.class)"
    @update:model-value="emit('update:modelValue', $event)"
    @complete="emit('complete', $event)"
  >
    <InputOTPGroup>
      <template v-for="index in length" :key="index">
        <InputOTPSeparator v-if="index - 1 === Math.floor(length / 2) && index - 1 > 0" />
        <InputOTPSlot :index="index - 1" class="h-10 w-10 rounded-lg text-base" />
      </template>
    </InputOTPGroup>
  </InputOTP>
</template>
